[package]
name = "crisper"
version = "0.1.0"
authors = ["Pranav Gaddamadugu <pranavsaig@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timely = "0.11.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spinach = { path = "../spinach" }
zmq = "0.9"

